### ISSUE TITLE
Update version and appindicator

### ISSUE THREAD

**Issue by renatomefi** [flathub/com.nordpass.NordPass#1]
Hello,

I've noticed that using NordPass via flatpak makes it not show up in the appindicator menu, is that a known issue?

Also, the version is quite outdated now compared with snap, is that something the publisher is not doing or can be done here?

Sorry about the newbie questions, I'm new to this ecosystem!

Thanks

**Comment by FakeShemp** [comment]
I'm not sure why the appindicator doesn't work. Which desktop environment do you use?

I've made a [merge request for a checker](https://github.com/flathub/flatpak-external-data-checker/pull/80) for Snapcraft packages, but it seem to be stuck at something. This would automatically update the flatpak as soon as the Snap is.

**Comment by renatomefi** [comment]
My system is Fedora 32 with gnome 3.36.2
Before I had Fedora 31 and gnome 3.34 and the same issue was there!

I could be using the snap version although I prefer flatpack, the problem is that with snap NordPass crashes with `./nordpass: error while loading shared libraries: libX11.so.6: cannot open shared object file: No such file or directory`

**Comment by FakeShemp** [comment]
I'm using Gnome as well and the indicator shows up fine for me.

I've updated the flatpak to latest version (#2).

**Comment by renatomefi** [comment]
Hey @FakeShemp, I've just updated the version and the app indicator now works, could be related to the old version!

Thanks so much for this!

One last thing I hope, the start on boot functionality does work (as I guess it's not mapped to the system one), is there a way to fix this either on the package itself or something I could do on my own system?

**Comment by FakeShemp** [comment]
I think that is handled by your OS in some way.
