### ISSUE TITLE
"Show in dock" option not remembrered on quit/reboot

### ISSUE THREAD

**Issue by codeSamuraii** [flathub/com.nordpass.NordPass#101]
I like my Dock only to contain apps that I use.
At startup or after quitting the app, the "Show in dock" option defaults to _checked_ and I have to toggle it again every time for the app to disappear from it.

Would it be possible for Nordpass to remember the selected choice at startup?

**Comment by FakeShemp** [comment]
For testing, which distro has a dock?

**Comment by codeSamuraii** [comment]
I run macOS 10.15.7

**Comment by codeSamuraii** [comment]
I realized this is not the official Nordpass repo but the Flatpack one, sorry.
